/**
 * Copyright (c) 2023, RTE (http://www.rte-france.com)
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 */
package com.powsybl.openreac.parameters.output.network;

import com.powsybl.ampl.converter.AmplConstants;
import com.powsybl.ampl.converter.AmplSubset;
import com.powsybl.commons.util.StringToIntMapper;
import com.powsybl.iidm.modification.ShuntCompensatorModification;
import com.powsybl.iidm.network.Network;
import com.powsybl.iidm.network.ShuntCompensator;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.*;

/**
 * @author Nicolas Pierre {@literal <nicolas.pierre at artelys.com>}
 */
public class ShuntCompensatorNetworkOutput extends AbstractNetworkOutput<ShuntCompensatorModification> {

    private static final Logger LOGGER = LoggerFactory.getLogger(ShuntCompensatorNetworkOutput.class);
    private static final String ELEMENT = "shunts";
    public static final int EXPECTED_COLS = 6;
    private static final int ID_COLUMN_INDEX = 1;
    private static final int B_COLUMN_INDEX = 3;
    private static final int BUS_COLUMN_INDEX = 2;
    private final List<ShuntWithDeltaDiscreteOptimalOverThreshold> shuntWithDeltaDiscreteOptimalOverThresholds = new ArrayList<>();
    private final double shuntCompensatorActivationAlertThreshold;
    /**
     * Continuous susceptance, in S, returned by the optimizer for each shunt compensator,
     * before it is discretized onto one of the sections the shunt actually provides.
     * Only covers the shunts present in the AMPL output and found in the network.
     */
    private final Map<String, Double> continuousSusceptanceByShunt = new HashMap<>();
    /**
     * Sum, over the shunts of {@link #reactiveDeviationByShunt}, of the absolute values of the
     * reactive power deviations, in MVar at nominal voltage. NaN as soon as one shunt carries
     * an invalid value.
     */
    private double totalAbsoluteReactiveDeviation = 0;
    /**
     * Signed reactive power deviation, in MVar at nominal voltage, introduced by discretizing
     * the continuous susceptance returned by the optimizer onto the sections available on each
     * shunt, per shunt compensator. Positive when the susceptance of the retained section is
     * greater than the continuous one, that is when the discretization increases the reactive
     * power generated by the shunt.
     * Only covers the shunts present in the AMPL output and found in the network.
     */
    private final Map<String, Double> reactiveDeviationByShunt = new HashMap<>();

    public record ShuntWithDeltaDiscreteOptimalOverThreshold(String id, int maximumSectionCount, double discretizedReactiveValue, double optimalReactiveValue) { }

    public ShuntCompensatorNetworkOutput(Network network, double shuntCompensatorActivationAlertThreshold) {
        super(network);
        this.shuntCompensatorActivationAlertThreshold = shuntCompensatorActivationAlertThreshold;
    }

    @Override
    public String getElement() {
        return ELEMENT;
    }

    @Override
    public int getExpectedColumns() {
        return EXPECTED_COLS;
    }

    @Override
    protected void readLine(String[] tokens, StringToIntMapper<AmplSubset> stringToIntMapper) {
        String id = stringToIntMapper.getId(AmplSubset.SHUNT, Integer.parseInt(tokens[ID_COLUMN_INDEX]));
        ShuntCompensator shuntCompensator = network.getShuntCompensator(id);
        if (!Objects.isNull(shuntCompensator)) {
            double b = readDouble(tokens[B_COLUMN_INDEX]) * AmplConstants.SB / Math.pow(shuntCompensator.getTerminal().getVoltageLevel().getNominalV(), 2);
            String busId = stringToIntMapper.getId(AmplSubset.BUS, Integer.parseInt(tokens[BUS_COLUMN_INDEX]));
            Boolean reconnect = null;
            if (busId != null && busId.equals(shuntCompensator.getTerminal().getBusView().getConnectableBus().getId())) {
                reconnect = true;
            }
            int sectionCount = findSectionCount(shuntCompensator, b);
            modifications.add(new ShuntCompensatorModification(id, reconnect, sectionCount));
            recordDiscretizationDeviation(shuntCompensator, b, sectionCount);
        } else {
            LOGGER.warn("Shunt compensator with id {} not found in the network", id);
        }
    }

    /**
     * As b is continuous in output files, we have to find the shunt closest section that matches with b.
     */
    private int findSectionCount(ShuntCompensator sc, double b) {
        double minDistance = Math.abs(b - sc.getB());
        double distance;
        int sectionCount = sc.getSectionCount();
        for (int i = 0; i <= sc.getMaximumSectionCount(); i++) {
            distance = Math.abs(b - sc.getB(i));
            if (distance < minDistance) {
                minDistance = distance;
                sectionCount = i;
            }
        }
        return sectionCount;
    }

    private void recordDiscretizationDeviation(ShuntCompensator sc, double b, int sectionCount) {
        double squaredNominalV = Math.pow(sc.getTerminal().getVoltageLevel().getNominalV(), 2);
        double optimalReactiveValue = Math.abs(b * squaredNominalV);
        double discretizedReactiveValue = Math.abs(sc.getB(sectionCount) * squaredNominalV);
        if (Math.abs(discretizedReactiveValue - optimalReactiveValue) > shuntCompensatorActivationAlertThreshold) {
            shuntWithDeltaDiscreteOptimalOverThresholds.add(new ShuntWithDeltaDiscreteOptimalOverThreshold(sc.getId(), sc.getMaximumSectionCount(), discretizedReactiveValue, optimalReactiveValue));
        }
        continuousSusceptanceByShunt.put(sc.getId(), b);
        double reactiveDeviation = (sc.getB(sectionCount) - b) * squaredNominalV;
        totalAbsoluteReactiveDeviation += Math.abs(reactiveDeviation);
        reactiveDeviationByShunt.put(sc.getId(), reactiveDeviation);
    }

    public List<ShuntWithDeltaDiscreteOptimalOverThreshold> getShuntsWithDeltaDiscreteOptimalOverThresholds() {
        return shuntWithDeltaDiscreteOptimalOverThresholds;
    }

    public Map<String, Double> getContinuousSusceptanceByShunt() {
        return Collections.unmodifiableMap(continuousSusceptanceByShunt);
    }

    public double getTotalAbsoluteReactiveDeviation() {
        return totalAbsoluteReactiveDeviation;
    }

    public Map<String, Double> getReactiveDeviationByShunt() {
        return Collections.unmodifiableMap(reactiveDeviationByShunt);
    }
}
